---
# install
- name: Ensure postfix is installed.
  yum:
    name: postfix
    state: installed

- name: Check default mailer.
  command: "/usr/bin/test /etc/alternatives/mta -ef /usr/sbin/sendmail.postfix"
  register: postfix_is_default_mailer
  changed_when: postfix_is_default_mailer.rc != 0

- name: Ensure sendmail is stopped and disabled to start at boot.
  service:
    name: sendmail
    state: stopped
    enabled: no
  when: postfix_is_default_mailer.rc != 0

- name: Copy postfix configuration in place.
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 00644
  notify:
    - restart postfix

- name: Ensure postfix is started and enabled to start at boot.
  service: name=postfix state=started enabled=yes

# SMTP-Auth
- name: Ensure cyrus-sasl packages are installed.
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ postfix_sasl_packages }}"

- name: Ensure saslauthd is started and enabled to start at boot.
  service: name=saslauthd state=started enabled=yes

- name: Copy sasl accounts file.
  template: src=sasl_passwd.j2 dest=/etc/postfix/sasl_passwd mode=0600
  register: sasl_accounts

- name: Update postmap.
  command: postmap hash:/etc/postfix/sasl_passwd
  when: sasl_accounts.changed
  notify:
    - restart postfix

# Mail dir
- name: Create skelton Maildir directory.
  file:
    path: "/etc/skel/Maildir/{{ item }}"
    state: directory
    mode: 00700
  with_items: [ new, cur, tmp ]
